python3: can't open file '/opt/domoticz/scripts/python/pushover.py': [Errno 2] No such file or directory
python3: can't open file '/opt/domoticz/scripts/python/pushover.py': [Errno 2] No such file or directory
python3: can't open file '/opt/domoticz/scripts/python/pushover.py': [Errno 2] No such file or directory
{"status":1,"request":"fb72d9a9-99ad-464f-86d2-63a2d4b97472"}
